cobaltcore-dev/aurora-dashboard

apps/aurora-portal/package.json
apps/aurora-portal/src/client/Compute/Compute.test.tsx
apps/aurora-portal/src/client/Compute/Compute.tsx
apps/aurora-portal/src/client/Shell/App.tsx
apps/aurora-portal/src/client/trpcClient.ts
apps/aurora-portal/src/polaris-bff/index.ts
apps/aurora-portal/src/polaris-bff/routers.ts
pnpm-lock.yaml

- Change 1
- Change 2
- Change 3
1. `pnpm i`

chore(core): add react query

---

apps/aurora-portal/package.json
apps/aurora-portal/src/client/Compute/Compute.test.tsx
apps/aurora-portal/src/client/Identity/Auth/Nav/Nav.tsx
apps/aurora-portal/src/client/Identity/Auth/Nav/index.ts
apps/aurora-portal/src/client/Identity/Auth/SignIn/SignIn.tsx
apps/aurora-portal/src/client/Identity/Auth/SignIn/index.ts
apps/aurora-portal/src/client/Identity/Overview/Overview.tsx
apps/aurora-portal/src/client/Identity/Overview/index.ts
apps/aurora-portal/src/client/Identity/Projects/Projects.tsx
apps/aurora-portal/src/client/Identity/Projects/index.ts
apps/aurora-portal/src/client/Identity/index.ts
apps/aurora-portal/src/client/Shell/App.tsx
apps/aurora-portal/src/client/Shell/Navigation/Navigation.tsx
apps/aurora-portal/src/polaris-bff/Compute/routers/serverRouter.ts
apps/aurora-portal/src/polaris-bff/Identity/routers/index.ts
apps/aurora-portal/src/polaris-bff/Identity/routers/tokenRouter.ts
apps/aurora-portal/src/polaris-bff/Identity/services/index.ts
apps/aurora-portal/src/polaris-bff/Identity/services/tokenApi.ts
apps/aurora-portal/src/polaris-bff/context.ts
apps/aurora-portal/src/polaris-bff/server.ts
apps/aurora-portal/src/polaris-bff/trpc.ts
pnpm-lock.yaml

This PR introduces the implementation of session management using Fastify's cookie plugin and tRPC context. It includes functions in the Identity Service API to handle login, logout, and session status, along with the corresponding user interface components.
---
- Integrated `@fastify/cookie` for session management.
- Created tRPC context to manage session-related actions, including `setSession` and `deleteSession`.
- Extended the Identity Service API to interact with the OpenStack Keystone API for authentication.
- Implemented a `tokenRouter` with the following endpoints:
- `login`: Authenticates users and sets the session cookie.
- `logout`: Clears the session cookie.
- `checkStatus`: Validates session state.
- Added UI components:
- Login screen for user authentication.
- User menu for …

feat(identity): add session cookie

---

docker/Dockerfile

This PR adds a LABEL to Dockerfile

chore(ci): add label to dockerfile to avoid errors in keppel

---

apps/aurora-portal/src/client/trpcClient.ts
apps/aurora-portal/src/polaris-bff/context.ts
apps/aurora-portal/src/polaris-bff/trpc.ts
packages/aurora-sdk/src/index.ts
packages/aurora-sdk/src/server/aurora-context.ts
packages/aurora-sdk/src/server/aurora-dev-context.ts
packages/aurora-sdk/src/server/aurora-provider.ts

This PR refactors the Aurora SDK by introducing an extendable `AuroraContext` type, which is utilized in extensions. Additionally, it implements `createDevContext` to facilitate extension development.  
- Introduced `AuroraContext` type for better extensibility  
- Updated `aurora-portal` to extend `AuroraContext`  
- Implemented `createDevContext` to support extension development  
1. `pnpm i`

chore(aurora-sdk): refactor sdk

---

apps/aurora-portal/.gitignore
apps/aurora-portal/src/client/Compute/Compute.test.tsx
apps/aurora-portal/src/client/Compute/Compute.tsx
apps/aurora-portal/src/client/Shell/AppContent.tsx
apps/aurora-portal/vite.config.mjs
pnpm-lock.yaml

This PR fixes a bug in compute introduced with the last change.
1. `pnpm i`

chore(aurora-portal): fix bug in compute

---

apps/aurora-portal/docs/Extensions.md
apps/aurora-portal/scripts/extensions/aurora-extension.ts
apps/aurora-portal/scripts/extensions/install.ts
apps/aurora-portal/src/server/routers.ts

This PR introduces the documentation for Aurora Extensions.
It covers the following topics:
- The interfaces for both the frontend and backend
- The main components of an extension and how to export them
- How to effectively use the **aurora-sdk** to integrate frontend and backend functionality

chore(docs): describe aurora extensions

---

packages/aurora-sdk/src/server/openstack-api.test.ts

This PR enhances test coverage for the OpenStack API in the **aurora-sdk**.
1. `pnpm i`

feat(aurora-sdk): add more tests

---

apps/aurora-portal/scripts/extensions/install.ts
apps/aurora-portal/src/client/Shell/AppContent.tsx
apps/aurora-portal/src/server/routers.ts

This PR introduces logic to handle scenarios where no extensions are provided.
- Defined the Extension interface to ensure proper handling of empty extensions during iteration.
- Enhanced robustness by adding safeguards for looping over empty extensions.
1. `pnpm i`

chore(core): handle empty extensions

---

apps/aurora-portal/src/client/Project/ProejctsOverview.tsx
apps/aurora-portal/src/client/Project/components/ProjectCardOverview.tsx
apps/aurora-portal/src/client/Project/components/ProjectCardView.tsx
apps/aurora-portal/src/client/Project/components/ProjectListView.test.tsx
apps/aurora-portal/src/client/Project/components/ProjectListView.tsx
apps/aurora-portal/src/client/Project/components/ProjectOverviewNavBar.tsx
apps/aurora-portal/src/client/Project/components/ProjectsCarView.test.tsx
apps/aurora-portal/src/client/Shell/AppContent.tsx
apps/aurora-portal/src/server/Project/routers/index.ts
apps/aurora-portal/src/server/Project/routers/projectRouter.ts
apps/aurora-portal/src/server/routers.ts
apps/aurora-portal/src/shared/types/models.ts

- Project View
- List View
- Card View
1. `pnpm i`

feat(aurora-portal): add projects overview

---

apps/aurora-portal/src/client/Auth/SignIn.tsx
apps/aurora-portal/src/client/Project/ProejctsOverview.tsx
apps/aurora-portal/src/client/Project/components/ProjectCardView.tsx
apps/aurora-portal/src/client/Project/components/ProjectListView.test.tsx
apps/aurora-portal/src/client/Project/components/ProjectListView.tsx
apps/aurora-portal/src/client/Project/components/ProjectsCarView.test.tsx
apps/aurora-portal/src/client/Shell/App.tsx
apps/aurora-portal/src/client/Shell/AppContent.tsx
apps/aurora-portal/src/client/Shell/AuroraProvider.tsx
apps/aurora-portal/src/client/Shell/AuthProvider.tsx
apps/aurora-portal/src/client/Shell/Navigation/AuroraNavigationToolbar.test.tsx
apps/aurora-portal/src/client/Shell/Navigation/AuroraNavigationToolbar.tsx
apps/aurora-portal/src/client/Shell/Navigation/MainNavigation.test.tsx
apps/aurora-portal/src/client/Shell/Navigation/MainNavigation.tsx
apps/aurora-portal/src/client/Shell/Navigation/NavigationLayout.tsx
apps/aurora-portal/src/client/Shell/Navigation/SubNavigation.tsx

Wouter navigation fix with proper highligh on active routing.
- Wouter highlight
- Navigation fix
- few issues left
- new sign in page
1. `pnpm i`

chore(aurora-portal): fix navigation and wouter

---

apps/aurora-portal/src/server/context.ts

use public endpoints for Openstack services by default.
1. `pnpm i`

chore(dashboard): use public endpoints as default

---

apps/aurora-portal/.gitignore
apps/aurora-portal/src/client/Network/components/TopologyChart.tsx
apps/aurora-portal/src/client/Network/components/drawSvg.d.ts
apps/aurora-portal/src/client/Network/components/drawSvg.js

Enhance the topology chart for better performance and improved visual clarity.
- **Prevent Redundant Loading**: Implemented checks to ensure the topology chart is not loaded multiple times, improving performance and reducing unnecessary computations.
- **Color Adjustments**: Updated the color scheme to enhance readability and visual appeal, ensuring that relevant elements are distinct and colorblind-friendly.
- **Label Positioning**: Repositioned labels for better alignment with data points, improving legibility and overall presentation of the chart.
1. `pnpm i`

chore(dashboard): improve the aesthetics of the topology chart.

---

apps/aurora-portal/src/client/Auth/AuthMenu.test.tsx
apps/aurora-portal/src/client/Auth/AuthMenu.tsx
apps/aurora-portal/src/client/Auth/SignIn.test.tsx
apps/aurora-portal/src/client/Auth/SignIn.tsx
apps/aurora-portal/src/client/Shell/AppContent.tsx
apps/aurora-portal/src/client/store/reducers/authReducer.test.ts
apps/aurora-portal/src/server/Authentication/routers/index.ts
apps/aurora-portal/src/server/Authentication/routers/sessionRouter.ts
apps/aurora-portal/src/server/Authentication/routers/tokenRouter.ts

Renamed queries and mutations in `tokenRouter` to adhere to the naming convention of "action + scope."
- **Renamed** `tokenRouter` to `sessionRouter`.
- **Updated** queries and mutations within `sessionRouter` to follow the new naming schema.
- **Added** tests for the `authReducer` to ensure functionality and maintain code quality.
- **Added** `setCurrentProject` function to the sessionRouter
- **Added** `setCurrentDomain` function to the sessionRouter
1. `pnpm i`

chore(dashboard): improve function names + tests

---

apps/aurora-portal/src/client/Project/ProejctsOverview.tsx
apps/aurora-portal/src/client/Shell/AuroraProvider.tsx
apps/aurora-portal/src/client/Shell/Home.tsx
apps/aurora-portal/src/client/Shell/Navigation/AuroraNavigationToolbar.test.tsx
apps/aurora-portal/src/client/Shell/Navigation/AuroraNavigationToolbar.tsx
apps/aurora-portal/src/server/Project/routers/projectRouter.ts
apps/aurora-portal/src/server/Project/types/models.test.js
apps/aurora-portal/src/server/Project/types/models.ts

This PR introduces Zod schemas for validating project-related data structures. It defines a base schema for a project, extends it to include hierarchical relationships, and structures the response schema for project lists. The implementation ensures type safety and data integrity. Additionally, tests have been included to verify schema validation behavior.
1. `pnpm i`

chore(core): introduce Zod-based project schema and response validation

---

apps/aurora-portal/package.json
apps/aurora-portal/src/client/Compute/components/ServerListView.tsx
apps/aurora-portal/src/client/Shell/App.tsx
apps/aurora-portal/src/client/Shell/NotificationCenter/AuroraToast.test.tsx
apps/aurora-portal/src/client/Shell/NotificationCenter/AuroraToast.tsx
apps/aurora-portal/src/client/components/Button.tsx
apps/aurora-portal/src/client/test-helper.tsx
pnpm-lock.yaml

This pull request introduces the `AuroraToast` component, a customizable toast notification system for displaying messages in the UI. It supports different variants, descriptions, and action buttons.  
- Implemented the `AuroraToast` component with support for success, error, warning, and info variants.  
- Added a `button` prop to allow action-based dismissals or interactions.  
- Integrated the component into the existing notification system.  
- Wrote unit tests to ensure proper rendering and interactions.  
Buttons in a compute section

chore(aurora-portal): add toast component

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/task.md

Github has introduced issue types recently. Having issue types is a nice improvement over our previous solution of using a custom field for issue types because this will now allow us to specify the matching issue type in our issue templates so that issues created with a template automatically set the correct `type` for the issue.
- Introduced new epic issue type
- Updated our project to use the `type` property rather than our old issue type custom field for filtering and sorting
- Updated all epics and all open issues with their correct type
- Updated issue templates to automatically set the correct type (this PR)

chore(config): update issue templates to auto assign type

---

apps/aurora-portal/src/client/Compute/ComputeOverview.tsx
apps/aurora-portal/src/client/Compute/Images/List.tsx
apps/aurora-portal/src/client/Compute/Instances/List.tsx
apps/aurora-portal/src/client/Compute/KeyPairs/List.tsx
apps/aurora-portal/src/client/Compute/ServerGroups/List.tsx
apps/aurora-portal/src/client/Shell/AuroraRouterConfig.tsx
apps/aurora-portal/src/client/Shell/Navigation/SubNavigation.tsx

- Change 1
- Change 2
- Change 3
1. `pnpm i`

chore(aurora-portal): add all compute modules

---

apps/aurora-portal/src/client/Shell/AuroraProvider.tsx
apps/aurora-portal/src/client/Shell/AuroraRouterConfig.tsx
apps/aurora-portal/src/client/Shell/DomainRescope.test.tsx
apps/aurora-portal/src/client/Shell/DomainRescope.tsx
apps/aurora-portal/src/client/Shell/Navigation/MainNavigation.test.tsx
apps/aurora-portal/src/client/Shell/Navigation/MainNavigation.tsx
apps/aurora-portal/src/client/Shell/Navigation/SubNavigation.test.tsx
apps/aurora-portal/src/server/Authentication/routers/sessionRouter.ts

This pull request refactors the domain display in the main navigation by removing the domain name and introducing a new `DomainScope` component for improved structure and maintainability.
- Removed the static domain name display from the main navigation
- Introduced a new `DomainScope` component to encapsulate domain logic
- Updated references and context usage to support the new structure
1. `pnpm i`

chore(aurora-portal): remove domain and proper scope name

---

apps/aurora-portal/package.json
apps/aurora-portal/src/client/trpcClient.ts
apps/aurora-portal/src/server/context.ts
apps/aurora-portal/src/server/server.ts
apps/aurora-portal/vite.config.mjs
packages/aurora-sdk/src/client/aurora-trpc.ts
pnpm-lock.yaml

This PR introduces CSRF protection to the Aurora Dashboard by utilizing the fastify/csrf-protection package. Additionally, it integrates the fastify/helmet package to enhance overall security by setting various HTTP headers.
1. Installed fastify/helmet and fastify/csrf-protection packages.
2. Configured the server to use the installed packages for enhanced security.
The fastify/helmet package helps secure the application by setting various HTTP headers, such as Content-Security-Policy, Strict-Transport-Security, and X-Frame-Options, to protect against common web vulnerabilities.
3. Extended the Aurora SDK to allow the headers property to be passed to the createTRPCClient function.
4. Implemented a call to /csrf-token on every tRPC request to ensure CSRF protection.
1. `pnpm i`
6. `pnpm …

feat(core): add csrf protection

---

apps/aurora-portal/package.json
apps/aurora-portal/src/client/routes/gardener.tsx
apps/aurora-portal/src/server/Gardener/client.ts
apps/aurora-portal/src/server/Gardener/routers/index.ts
apps/aurora-portal/src/server/Gardener/routers/shootRouter.ts
apps/aurora-portal/src/server/Gardener/types/cluster.ts
apps/aurora-portal/src/server/Gardener/types/shoot.ts
apps/aurora-portal/src/server/routers.ts
pnpm-lock.yaml

This pull request (PR) introduces the Backend-for-Frontend (BFF) component for Gardener. With this implementation, we can now communicate with the Gardener backend.
- BFF Integration: The BFF component is now set up to handle communication with the Gardener backend.
- Hardcoded Credentials: For the initial implementation, the credentials are hardcoded in the .env file. This is a temporary measure.
- Dynamic Credential Management: In future iterations, we plan to replace the hardcoded credentials with a more secure and dynamic credential management system.
1. `pnpm i`

feat(bff): add bff part for gardener

---

apps/aurora-portal/src/client/routeTree.gen.ts
apps/aurora-portal/src/client/routes/test.tsx
apps/aurora-portal/src/server/Gardener/routers/shootRouter.ts
apps/aurora-portal/src/server/Gardener/types/shootApiSchema.ts

This pull request completes the implementation of all CRUD (Create, Read, Update, Delete) operations in the Gardener Backend-for-Frontend (BFF) layer.
1. `pnpm i`

chore(bff): finalize CRUD actions in bff for gardener

---

apps/aurora-portal/src/client/components/Spiner.tsx
apps/aurora-portal/src/client/components/headless-ui/Select.tsx
apps/aurora-portal/src/client/routes/__root.tsx
apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/Images/List.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/BasicInfoStep.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/InfrastructureStep.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/ReviewStep.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/WizardActions.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/WizardHeader.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/WizardProgress.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/WorkerNodesStep.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/WorkerPool.tsx
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/constants.ts
apps/aurora-portal/src/client/routes/gardener/-components/ClusterWizard/types.ts
apps/aurora-portal/src/client/routes/gardener/-components/CreateClusterDialog.tsx
apps/aurora-portal/src/client/routes/gardener/-components/GardenerDialog.tsx
apps/aurora-portal/src/client/routes/gardener/clusters/index.tsx
apps/aurora-portal/src/server/Gardener/routers/shootRouter.ts

- Change 1
- Change 2
- Change 3
1. `pnpm i`

chore(gardener): add dialog 

---

apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/-components/ProjectOverviewNavBar.tsx
apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/index.tsx
apps/aurora-portal/src/server/Project/routers/projectRouter.ts

Implement search functionality for the search bar on the Project Overview page using TanStack Router's search parameters.
- Reviewed TanStack Router's search param documentation and defined a search schema.
- Implemented the search bar using controlled input linked to router search parameters.
- Updated the `ProjectListView` to respond to search changes and filter results accordingly.
- Ensured search state is URL-driven and persists across navigation and reloads.
Closes #118 
1. `pnpm i`

feat(dashboard): search with corresponding bff 

---

apps/aurora-portal/src/server/Gardener/types/cloudProfile.test.ts
apps/aurora-portal/src/server/Gardener/types/cluster.test.ts
apps/aurora-portal/src/server/Gardener/types/cluster.ts

This PR adds a new property to the cluster "stateDetails" which allows to display the reason of a state transition as well as the progress. 
1. `pnpm i`

chore(bff): implement delete and create actions for gardener bff

---

apps/aurora-portal/src/client/AppContent.tsx
apps/aurora-portal/src/client/router.ts
apps/aurora-portal/src/client/routes/_auth/accounts/index.tsx
apps/aurora-portal/src/client/routes/index.tsx
apps/aurora-portal/src/client/store/AuthProvider.tsx

Warning "useRouter must be used inside a <RouterProvider> component!" solved by resolving circular dependencies.
Automatic logins through correct reconnects and checks inside of __auth
New router File
New reconnects
closes #202 
1. `pnpm i`

fix(dashboard): seperate router to ensure there is no circular dependency

---

apps/aurora-portal/src/client/components/navigation/MainNavigation.test.tsx
apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/ComponentNavBar.test.tsx
apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/Images/-components/CreateImageModal.test.tsx
apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/Images/-components/EditImageDialog.test.tsx
apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/-components/ProjectOverviewNavBar.test.tsx

This pull request includes fixes for the unit test errors, focusing on removing unnecessary warnings from the test output. The purpose of these changes is to ensure that the test output is clean and free of extraneous warnings, improving the clarity and reliability of test results.
- Fixed unit test errors.
- Ensured test output does not contain unnecessary warnings.
The changes improve the quality and readability of test output without introducing new features or impacting existing functionality outside of the tests.
1. `pnpm i`

test(ui): clean-up unit test output (fix warnings and errors)

---

apps/aurora-portal/docs/003_flavors_ui_requirements.md

This PR adds a requirements document  for flavors UI.

chore(docs): add requirements document for flavors ui

---

apps/aurora-portal/docs/004_proposal_subscriptions.md

closes #260 
This PR addresses the GitHub issue by creating a comprehensive proposal document for integrating tRPC subscriptions into the BFF layer to enable real-time data updates. The proposal evaluates Server-Sent Events (SSE) as the primary transport mechanism and provides a complete architectural solution for real-time updates in the aurora-portal application.
- Created `0004_proposal_subscriptions.md` in the `aurora-portal/docs/` folder
- Documented a complete SSE-based architecture for real-time updates
- Evaluated transport mechanisms with SSE as the recommended solution
- Defined integration patterns for both server and client sides
- Outlined system components including UpdateService, BackgroundWorker, and SSE Router
- Provided detailed implementation examples for backend and …

research(core): create Proposal for Integrating tRPC Subscriptions in BFF Layer

---

apps/aurora-portal/src/server/Compute/helpers/imageHelpers.test.ts
apps/aurora-portal/src/server/Compute/helpers/imageHelpers.ts
apps/aurora-portal/src/server/Compute/routers/imageRouter.test.ts
apps/aurora-portal/src/server/Compute/routers/imageRouter.ts

Improves error handling when the backend-for-frontend (BFF) service interacts with OpenStack APIs for image operations. This change ensures more robust error responses and better debugging capabilities when image-related requests fail.
- Enhanced error catching and logging for OpenStack image API calls
- Improved error message formatting for client responses
- Added proper error status code mapping
- #382
1. `pnpm i`

fix(bff): improve error handling (images bff)
